package hmi;

import java.text.DecimalFormat;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author jnane
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form gui
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdTotalCarbon = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jlTotalCO2Emission = new javax.swing.JLabel();
        jbjdOk = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtCarsAvgMileage = new NumericTextField();
        jLabel2 = new javax.swing.JLabel();
        jtMilesViaPublicTrPerWeek = new NumericTextField();
        jLabel3 = new javax.swing.JLabel();
        jtTotalDistbyFlightPerYear_Miles = new NumericTextField();
        jtAvgElectricityUsageMnthly_kwh = new NumericTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtAvgMonthlyGasUsage_therms = new NumericTextField();
        jbCalulate = new javax.swing.JButton();
        jbClear = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        JtAvgMonthlyFoodExpenses = new NumericTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        jdTotalCarbon.setTitle("Total CO2 Emission");
        jdTotalCarbon.setAlwaysOnTop(true);
        jdTotalCarbon.setMaximumSize(new java.awt.Dimension(400, 300));
        jdTotalCarbon.setMinimumSize(new java.awt.Dimension(400, 300));
        jdTotalCarbon.setResizable(false);

        jLabel4.setText("Total Carbon Emission:");

        jlTotalCO2Emission.setText(" ");

        jbjdOk.setText("Ok");
        jbjdOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbjdOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jdTotalCarbonLayout = new javax.swing.GroupLayout(jdTotalCarbon.getContentPane());
        jdTotalCarbon.getContentPane().setLayout(jdTotalCarbonLayout);
        jdTotalCarbonLayout.setHorizontalGroup(
            jdTotalCarbonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdTotalCarbonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdTotalCarbonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbjdOk)
                    .addComponent(jlTotalCO2Emission, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jdTotalCarbonLayout.setVerticalGroup(
            jdTotalCarbonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdTotalCarbonLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jdTotalCarbonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jlTotalCO2Emission))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jbjdOk)
                .addGap(53, 53, 53))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculate Co2 Emission");

        jLabel1.setText("Cars Average Mileage (Miles per gallon)");

        NumericTextField c_jtCarsAvgMileage = (NumericTextField) jtCarsAvgMileage;
        jtCarsAvgMileage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCarsAvgMileageActionPerformed(evt);
            }
        });

        jLabel2.setText("Number Miles travel by public transport per week");

        jLabel3.setText("Total distance Fly by flight per Year in Miles");

        jLabel5.setText("Average Electricity Usage Monthly in KiloWats per hour");

        jLabel6.setText("Average Monthly Gas usage in therms");

        jbCalulate.setText("Calculate");
        jbCalulate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalulateActionPerformed(evt);
            }
        });

        jbClear.setText("Clear");
        jbClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbClearActionPerformed(evt);
            }
        });

        jLabel7.setText("Monthly Food Expenses");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbClear)
                        .addGap(66, 66, 66)
                        .addComponent(jbCalulate))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtCarsAvgMileage, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(34, 34, 34)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtTotalDistbyFlightPerYear_Miles, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtMilesViaPublicTrPerWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtAvgElectricityUsageMnthly_kwh, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtAvgMonthlyGasUsage_therms, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JtAvgMonthlyFoodExpenses, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtCarsAvgMileage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtMilesViaPublicTrPerWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtTotalDistbyFlightPerYear_Miles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtAvgMonthlyGasUsage_therms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtAvgElectricityUsageMnthly_kwh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(JtAvgMonthlyFoodExpenses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCalulate)
                    .addComponent(jbClear))
                .addGap(21, 21, 21))
        );

        jTabbedPane2.addTab("Input", jPanel1);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("View");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Help");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbjdOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbjdOkActionPerformed
      jdTotalCarbon.show(false);
      jdTotalCarbon.hide();
    }//GEN-LAST:event_jbjdOkActionPerformed

    private void jbClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbClearActionPerformed
        // TODO add your handling code here:
        String text = "";
        jtAvgElectricityUsageMnthly_kwh.setText(text);
        jtAvgMonthlyGasUsage_therms.setText(text);
        jtCarsAvgMileage.setText(text);
        jtMilesViaPublicTrPerWeek.setText(text);
        jtTotalDistbyFlightPerYear_Miles.setText(text);
        JtAvgMonthlyFoodExpenses.setText(text);
        jlTotalCO2Emission.setText(text);
    }//GEN-LAST:event_jbClearActionPerformed

    private void jbCalulateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalulateActionPerformed
        double electricity_usage;
        electricity_usage = ((NumericTextField) jtAvgElectricityUsageMnthly_kwh).getDouble();
        ((NumericTextField) jtMilesViaPublicTrPerWeek).getDouble();
        ((NumericTextField) jtTotalDistbyFlightPerYear_Miles).getDouble();
        double miles_emissions = ((NumericTextField) jtCarsAvgMileage).getDouble() * 0.404;
        double home_emissions = ((NumericTextField) jtAvgMonthlyGasUsage_therms).getDouble()
        * (0.63 * electricity_usage + 0.25 * ((NumericTextField) jtAvgMonthlyGasUsage_therms).getDouble()) / 12;
        double food_emissions = ((NumericTextField) jtMilesViaPublicTrPerWeek).getDouble() * 0.129;
        // Output total carbon emissions
        double total_emissions = miles_emissions + home_emissions + food_emissions;
        DecimalFormat decimalFormat = new DecimalFormat("#.##");
        jlTotalCO2Emission.setText(String.format("%.2f", total_emissions));
        jdTotalCarbon.show(true);
    }//GEN-LAST:event_jbCalulateActionPerformed

    private void jtCarsAvgMileageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCarsAvgMileageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCarsAvgMileageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JtAvgMonthlyFoodExpenses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton jbCalulate;
    private javax.swing.JButton jbClear;
    private javax.swing.JButton jbjdOk;
    private javax.swing.JDialog jdTotalCarbon;
    private javax.swing.JLabel jlTotalCO2Emission;
    private javax.swing.JTextField jtAvgElectricityUsageMnthly_kwh;
    private javax.swing.JTextField jtAvgMonthlyGasUsage_therms;
    private javax.swing.JTextField jtCarsAvgMileage;
    private javax.swing.JTextField jtMilesViaPublicTrPerWeek;
    private javax.swing.JTextField jtTotalDistbyFlightPerYear_Miles;
    // End of variables declaration//GEN-END:variables
}
